package org.rag4j.agent.reasoning;

import org.rag4j.agent.core.Conversation;

/**
 * Reasoning interface for processing user messages within a conversation.
 * <p>
 * This interface defines a method to reason about a user's message and return a response
 * based on the context of the conversation.
 */
public interface Reasoning {

    /**
     * Processes a user's message within the context of a conversation and returns a response.
     *
     * @param userMessage   the user's message to reason about
     * @param conversation  the current conversation context
     * @return a response message generated by the reasoning process
     */
    Conversation.Message reason(Conversation.Message userMessage, Conversation conversation);
}
