spring:
  profiles:
    active: plain
  application:
    name: agent-workshop-assignments


openai:
  proxy:
    url: https://vfjv12h3xb.execute-api.eu-west-1.amazonaws.com
#    url:
    token:
    password: ${WORKSHOP_PASSWORD:}
    user-id: workshop-default
    cache:
      enabled: true
      location: ${user.dir}/data/token-cache.json

logging:
  level:
    root: INFO
    org.rag4j.agent: INFO
    org.springframework.ai: INFO


agent:
  plain:
    reasoning:
      max-reasoning-steps: 5
    memory:
      max-conversation-size: 10
